name: 'Pull Request: Continuous Integration'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-bicep-build-and-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate main.bicep builds
      uses: azure/CLI@v1
      with:
        # if local committed builds don't align with the latest bicep generator template hash
        # bump this version to the most recent via: https://github.com/Azure/azure-cli/releases
        azcliversion: 2.36.0
        inlineScript: |
          az bicep build --file main.bicep --outfile deploy_me.json

    - name: Verify Bicep ARM template compilation hash
      shell: pwsh
      run: |
        $committedTemplate = Get-Content azuredeploy.json | ConvertFrom-Json
        $ciTemplate = Get-Content deploy_me.json | ConvertFrom-Json

        $committedHash = $committedTemplate.metadata._generator.templateHash
        $ciHash = $ciTemplate.metadata._generator.templateHash

        $committedUsingVersion = $committedTemplate.metadata._generator.version
        $ciUsingVersion = $ciTemplate.metadata._generator.version

        if ($committedHash -ne $ciHash) {
          Write-Error "Current committed template hash ($committedHash) and hash of the CI-built template hash ($ciHash) are not the same.`n" `
            + "This could be due to your local Bicep version ($committedUsingVersion) and the one used by the CI container ($ciUsingVersion) are different."

          exit 1
        } else {
          Write-Host 'Template hashes validated.'
        }

    - name: Login to AZ CLI
      run: |
        az login --service-principal -t ${{ secrets.AZURE_CLIENT_TENANT }} -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}

    - name: Run ARM deployment validation
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}-${{ github.run_id }}-${{ github.run_attempt }}
        region: Norway East
        deploymentMode: Validate
        template: ./deploy_me.json

  test-stream-analytics-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prerequisites
      shell: pwsh
      run: |
        npm install -g azure-streamanalytics-cicd

    - name: Run all tests
      shell: pwsh
      run: ./scripts/Invoke-StreamAnalyticsTests.ps1
