name: 'Continuous Integration'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

# https://docs.github.com/actions/reference/workflows-and-actions/workflow-syntax#permissions
# > If you specify the access for any of these permissions (contents, issues, pull-requests, etc.),
# > all of those that are not specified are set to none.
permissions:
  contents: read # required for actions/checkout to work

jobs:
  validate-bicep-builds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build Bicep
      uses: azure/CLI@9eb25b8360668fb0ecbafa808d40e2197b2f5f52 # v3.0.0
      with:
        inlineScript: |
          az bicep build --file main.bicep --outfile _ci_generated_azuredeploy.json

    - name: Assert ARM template correctness
      shell: pwsh
      run: ./scripts/Assert-ARMTemplateCorrectness.ps1

  test-stream-analytics-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup .NET 6 (deprecated version required for ASA)
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        # Must remain on .NET 6 for now, as Azure Stream Analytics does not support a higher runtime (see https://github.com/microsoft/vscode-asa/issues/119)
        dotnet-version: '6.0.x'

    - name: Prerequisites
      shell: pwsh
      run: |
        npm install -g azure-streamanalytics-cicd

    - name: Run all tests
      shell: pwsh
      run: ./scripts/Invoke-StreamAnalyticsTests.ps1
