name: 'Continuous Integration'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-bicep-builds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az bicep build --file main.bicep --outfile _ci_generated_azuredeploy.json

    - name: Assert ARM template correctness
      shell: pwsh
      run: ./scripts/Assert-ARMTemplateCorrectness.ps1

  test-stream-analytics-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v5
      with:
        # Must remain on .NET 6 for now, as Azure Stream Analytics does not support a higher runtime (see https://github.com/microsoft/vscode-asa/issues/119)
        dotnet-version: '6.0.x'

    - name: Prerequisites
      shell: pwsh
      run: |
        npm install -g azure-streamanalytics-cicd

    - name: Run all tests
      shell: pwsh
      run: ./scripts/Invoke-StreamAnalyticsTests.ps1
