name: 'Pull Request: Continuous Integration'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-bicep-build-and-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate main.bicep builds
      uses: azure/CLI@v1
      with:
        azcliversion: 2.36.0
        inlineScript: |
          az bicep build --file main.bicep --outfile deploy_me.json

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deployment validation
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}-${{ github.run_id }}-${{ github.run_attempt }}
        region: Norway East
        deploymentMode: Validate
        template: ./deploy_me.json

  test-stream-analytics-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prerequisites
      shell: pwsh
      run: |
        npm install -g azure-streamanalytics-cicd

    - name: Run all tests
      shell: pwsh
      run: ./scripts/Invoke-StreamAnalyticsTests.ps1
