name: 'Continuous Integration'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

# https://docs.github.com/actions/reference/workflows-and-actions/workflow-syntax#permissions
# > If you specify the access for any of these permissions (contents, issues, pull-requests, etc.),
# > all of those that are not specified are set to none.
permissions:
  contents: read # required for actions/checkout to work

jobs:
  validate-bicep-builds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az bicep build --file main.bicep --outfile _ci_generated_azuredeploy.json

    - name: Assert ARM template correctness
      shell: pwsh
      run: ./scripts/Assert-ARMTemplateCorrectness.ps1

  test-stream-analytics-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Prerequisites
      shell: pwsh
      run: |
        npm install -g azure-streamanalytics-cicd

    - name: Run all tests
      shell: pwsh
      run: ./scripts/Invoke-StreamAnalyticsTests.ps1
